apiVersion: v1
kind: Secret
metadata:
  name: metro-planner-db-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: eWFzaGFzQG15c3FsLWFzaGFz  # base64 of 'yashas@mysql-yashas'
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmRAMTIz           # base64 of 'password@123'