TRUNCATE TABLE station;

-- Purple Line
INSERT INTO station (id, city, name, line, active, code) VALUES (1, 'Bangalore', 'Whitefield (Kadugodi)', 'Purple', 'Y', 'WHF');
INSERT INTO station (id, city, name, line, active, code) VALUES (2, 'Bangalore', 'Hopefarm Channasandra', 'Purple', 'Y', 'HFC');
INSERT INTO station (id, city, name, line, active, code) VALUES (3, 'Bangalore', 'Kadugodi Tree Park', 'Purple', 'Y', 'KTP');
INSERT INTO station (id, city, name, line, active, code) VALUES (4, 'Bangalore', 'Pattandur Agrahara', 'Purple', 'Y', 'PAT');
INSERT INTO station (id, city, name, line, active, code) VALUES (5, 'Bangalore', 'Sri Sathya Sai Hospital', 'Purple', 'Y', 'SSSH');
INSERT INTO station (id, city, name, line, active, code) VALUES (6, 'Bangalore', 'Nallurhalli', 'Purple', 'Y', 'NAL');
INSERT INTO station (id, city, name, line, active, code) VALUES (7, 'Bangalore', 'Kundalahalli', 'Purple', 'Y', 'KDH');
INSERT INTO station (id, city, name, line, active, code) VALUES (8, 'Bangalore', 'Seetharampalya', 'Purple', 'Y', 'STR');
INSERT INTO station (id, city, name, line, active, code) VALUES (9, 'Bangalore', 'Hoodi', 'Purple', 'Y', 'HOD');
INSERT INTO station (id, city, name, line, active, code) VALUES (10, 'Bangalore', 'Garudacharpalya', 'Purple', 'Y', 'GCP');
INSERT INTO station (id, city, name, line, active, code) VALUES (11, 'Bangalore', 'Singayyanapalya', 'Purple', 'Y', 'SGP');
INSERT INTO station (id, city, name, line, active, code) VALUES (12, 'Bangalore', 'Krishnarajapura', 'Purple', 'Y', 'KRP');
INSERT INTO station (id, city, name, line, active, code) VALUES (13, 'Bangalore', 'Benniganahalli', 'Purple', 'Y', 'BGH');
INSERT INTO station (id, city, name, line, active, code) VALUES (14, 'Bangalore', 'Baiyappanahalli', 'Purple', 'Y', 'BPN');
INSERT INTO station (id, city, name, line, active, code) VALUES (15, 'Bangalore', 'Swami Vivekananda Road', 'Purple', 'Y', 'SVR');
INSERT INTO station (id, city, name, line, active, code) VALUES (16, 'Bangalore', 'Indiranagar', 'Purple', 'Y', 'IND');
INSERT INTO station (id, city, name, line, active, code) VALUES (17, 'Bangalore', 'Halasuru', 'Purple', 'Y', 'HLS');
INSERT INTO station (id, city, name, line, active, code) VALUES (18, 'Bangalore', 'Trinity', 'Purple', 'Y', 'TRI');
INSERT INTO station (id, city, name, line, active, code) VALUES (19, 'Bangalore', 'Mahatma Gandhi Road', 'Purple', 'Y', 'MGR');
INSERT INTO station (id, city, name, line, active, code) VALUES (20, 'Bangalore', 'Cubbon Park', 'Purple', 'Y', 'CBP');
INSERT INTO station (id, city, name, line, active, code) VALUES (21, 'Bangalore', 'Vidhana Soudha', 'Purple', 'Y', 'VDS');
INSERT INTO station (id, city, name, line, active, code) VALUES (22, 'Bangalore', 'Central College', 'Purple', 'Y', 'CLC');
INSERT INTO station (id, city, name, line, active, code) VALUES (23, 'Bangalore', 'Majestic', 'Purple', 'Y', 'MJT');
INSERT INTO station (id, city, name, line, active, code) VALUES (24, 'Bangalore', 'Krantivira Sangolli Rayanna Railway Station', 'Purple', 'Y', 'KSR');
INSERT INTO station (id, city, name, line, active, code) VALUES (25, 'Bangalore', 'Magadi Road', 'Purple', 'Y', 'MGRD');
INSERT INTO station (id, city, name, line, active, code) VALUES (26, 'Bangalore', 'Sri Balagangadharanatha Swamiji Station, Hosahalli', 'Purple', 'Y', 'SBSH');
INSERT INTO station (id, city, name, line, active, code) VALUES (27, 'Bangalore', 'Vijayanagara', 'Purple', 'Y', 'VJN');
INSERT INTO station (id, city, name, line, active, code) VALUES (28, 'Bangalore', 'Attiguppe', 'Purple', 'Y', 'ATT');
INSERT INTO station (id, city, name, line, active, code) VALUES (29, 'Bangalore', 'Deepanjali Nagar', 'Purple', 'Y', 'DPN');
INSERT INTO station (id, city, name, line, active, code) VALUES (30, 'Bangalore', 'Mysuru Road', 'Purple', 'Y', 'MYR');
INSERT INTO station (id, city, name, line, active, code) VALUES (31, 'Bangalore', 'Pantharapalya - Nayandahalli', 'Purple', 'Y', 'PNH');
INSERT INTO station (id, city, name, line, active, code) VALUES (32, 'Bangalore', 'Rajarajeshwari Nagar', 'Purple', 'Y', 'RRN');
INSERT INTO station (id, city, name, line, active, code) VALUES (33, 'Bangalore', 'Jnanabharathi', 'Purple', 'Y', 'JNB');
INSERT INTO station (id, city, name, line, active, code) VALUES (34, 'Bangalore', 'Pattanagere', 'Purple', 'Y', 'PTG');
INSERT INTO station (id, city, name, line, active, code) VALUES (35, 'Bangalore', 'Kengeri Bus Terminal', 'Purple', 'Y', 'KBT');
INSERT INTO station (id, city, name, line, active, code) VALUES (36, 'Bangalore', 'Kengeri', 'Purple', 'Y', 'KEN');
INSERT INTO station (id, city, name, line, active, code) VALUES (37, 'Bangalore', 'Challaghatta', 'Purple', 'Y', 'CHG');

-- Green Line
INSERT INTO station (id, city, name, line, active, code) VALUES (38, 'Bangalore', 'Madavara', 'Green', 'Y', 'MDV');
INSERT INTO station (id, city, name, line, active, code) VALUES (39, 'Bangalore', 'Chikkabidarakallu', 'Green', 'Y', 'CKB');
INSERT INTO station (id, city, name, line, active, code) VALUES (40, 'Bangalore', 'Manjunath Nagar', 'Green', 'Y', 'MJN');
INSERT INTO station (id, city, name, line, active, code) VALUES (41, 'Bangalore', 'Nagasandra', 'Green', 'Y', 'NGS');
INSERT INTO station (id, city, name, line, active, code) VALUES (42, 'Bangalore', 'Dasarahalli', 'Green', 'Y', 'DSH');
INSERT INTO station (id, city, name, line, active, code) VALUES (43, 'Bangalore', 'Jalahalli', 'Green', 'Y', 'JHL');
INSERT INTO station (id, city, name, line, active, code) VALUES (44, 'Bangalore', 'Peenya Industry', 'Green', 'Y', 'PNI');
INSERT INTO station (id, city, name, line, active, code) VALUES (45, 'Bangalore', 'Peenya', 'Green', 'Y', 'PNY');
INSERT INTO station (id, city, name, line, active, code) VALUES (46, 'Bangalore', 'Goraguntepalya', 'Green', 'Y', 'GRT');
INSERT INTO station (id, city, name, line, active, code) VALUES (47, 'Bangalore', 'Yeshwanthpura', 'Green', 'Y', 'YSP');
INSERT INTO station (id, city, name, line, active, code) VALUES (48, 'Bangalore', 'Sandal Soap Factory', 'Green', 'Y', 'SSF');
INSERT INTO station (id, city, name, line, active, code) VALUES (49, 'Bangalore', 'Mahalakshmi', 'Green', 'Y', 'MHK');
INSERT INTO station (id, city, name, line, active, code) VALUES (50, 'Bangalore', 'Rajajinagar', 'Green', 'Y', 'RJG');
INSERT INTO station (id, city, name, line, active, code) VALUES (51, 'Bangalore', 'Mahakavi Kuvempu Road', 'Green', 'Y', 'MKR');
INSERT INTO station (id, city, name, line, active, code) VALUES (52, 'Bangalore', 'Srirampura', 'Green', 'Y', 'SRP');
INSERT INTO station (id, city, name, line, active, code) VALUES (53, 'Bangalore', 'Mantri Square Sampige Road', 'Green', 'Y', 'MSS');
INSERT INTO station (id, city, name, line, active, code) VALUES (54, 'Bangalore', 'Majestic', 'Green', 'Y', 'MJT');
INSERT INTO station (id, city, name, line, active, code) VALUES (55, 'Bangalore', 'Chickpete', 'Green', 'Y', 'CKP');
INSERT INTO station (id, city, name, line, active, code) VALUES (56, 'Bangalore', 'Krishna Rajendra Market', 'Green', 'Y', 'KRM');
INSERT INTO station (id, city, name, line, active, code) VALUES (57, 'Bangalore', 'National College', 'Green', 'Y', 'NCL');
INSERT INTO station (id, city, name, line, active, code) VALUES (58, 'Bangalore', 'Lalbagh', 'Green', 'Y', 'LBG');
INSERT INTO station (id, city, name, line, active, code) VALUES (59, 'Bangalore', 'South End Circle', 'Green', 'Y', 'SEC');
INSERT INTO station (id, city, name, line, active, code) VALUES (60, 'Bangalore', 'Jayanagar', 'Green', 'Y', 'JNR');
INSERT INTO station (id, city, name, line, active, code) VALUES (61, 'Bangalore', 'Rashtreeya Vidyalaya Road', 'Green', 'Y', 'RVR');
INSERT INTO station (id, city, name, line, active, code) VALUES (62, 'Bangalore', 'Banashankari', 'Green', 'Y', 'BNS');
INSERT INTO station (id, city, name, line, active, code) VALUES (63, 'Bangalore', 'Jayaprakash Nagar', 'Green', 'Y', 'JPN');
INSERT INTO station (id, city, name, line, active, code) VALUES (64, 'Bangalore', 'Yelachenahalli', 'Green', 'Y', 'YCH');
INSERT INTO station (id, city, name, line, active, code) VALUES (65, 'Bangalore', 'Konanakunte Cross', 'Green', 'Y', 'KNC');
INSERT INTO station (id, city, name, line, active, code) VALUES (66, 'Bangalore', 'Doddakallasandra', 'Green', 'Y', 'DKS');
INSERT INTO station (id, city, name, line, active, code) VALUES (67, 'Bangalore', 'Kengeri', 'Green', 'Y', 'KEN');
INSERT INTO station (id, city, name, line, active, code) VALUES (68, 'Bangalore', 'Thalaghattapura', 'Green', 'Y', 'THP');
INSERT INTO station (id, city, name, line, active, code) VALUES (69, 'Bangalore', 'Silk Institute', 'Green', 'Y', 'SIL');

-- Yellow Line
INSERT INTO station (id, city, name, line, active, code) VALUES (70, 'Bangalore', 'Rashtreeya Vidyalaya Road', 'Yellow', 'Y', 'RVR');
INSERT INTO station (id, city, name, line, active, code) VALUES (71, 'Bangalore', 'Ragigudda', 'Yellow', 'Y', 'RGD');
INSERT INTO station (id, city, name, line, active, code) VALUES (72, 'Bangalore', 'Jayadeva Hospital', 'Yellow', 'Y', 'JVH');
INSERT INTO station (id, city, name, line, active, code) VALUES (73, 'Bangalore', 'BTM Layout', 'Yellow', 'Y', 'BTM');
INSERT INTO station (id, city, name, line, active, code) VALUES (74, 'Bangalore', 'Central Silk Board', 'Yellow', 'Y', 'CSB');
INSERT INTO station (id, city, name, line, active, code) VALUES (75, 'Bangalore', 'Bommanahalli', 'Yellow', 'Y', 'BMN');
INSERT INTO station (id, city, name, line, active, code) VALUES (76, 'Bangalore', 'Hongasandra', 'Yellow', 'Y', 'HGS');
INSERT INTO station (id, city, name, line, active, code) VALUES (77, 'Bangalore', 'Kudlu Gate', 'Yellow', 'Y', 'KDG');
INSERT INTO station (id, city, name, line, active, code) VALUES (78, 'Bangalore', 'Singasandra', 'Yellow', 'Y', 'SGS');
INSERT INTO station (id, city, name, line, active, code) VALUES (79, 'Bangalore', 'Hosa Road', 'Yellow', 'Y', 'HSR');
INSERT INTO station (id, city, name, line, active, code) VALUES (80, 'Bangalore', 'Beratena Agrahara', 'Yellow', 'Y', 'BAG');
INSERT INTO station (id, city, name, line, active, code) VALUES (81, 'Bangalore', 'Electronic City', 'Yellow', 'Y', 'ELC');
INSERT INTO station (id, city, name, line, active, code) VALUES (82, 'Bangalore', 'Infosys Foundation Konappana Agrahara', 'Yellow', 'Y', 'IFK');
INSERT INTO station (id, city, name, line, active, code) VALUES (83, 'Bangalore', 'Huskur Road', 'Yellow', 'Y', 'HSK');
INSERT INTO station (id, city, name, line, active, code) VALUES (84, 'Bangalore', 'Biocon Hebbagodi', 'Yellow', 'Y', 'BHB');
INSERT INTO station (id, city, name, line, active, code) VALUES (85, 'Bangalore', 'Delta Electronics Bommasandra', 'Yellow', 'Y', 'DEB');
