TRUNCATE TABLE station;

-- Purple Line
INSERT INTO station (id, city, name, line, active) VALUES (1, 'Bangalore', 'Whitefield (Kadugodi)', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (2, 'Bangalore', 'Hopefarm Channasandra', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (3, 'Bangalore', 'Kadugodi Tree Park', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (4, 'Bangalore', 'Pattandur Agrahara', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (5, 'Bangalore', 'Sri Sathya Sai Hospital', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (6, 'Bangalore', 'Nallurhalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (7, 'Bangalore', 'Kundalahalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (8, 'Bangalore', 'Seetharampalya', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (9, 'Bangalore', 'Hoodi', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (10, 'Bangalore', 'Garudacharpalya', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (11, 'Bangalore', 'Singayyanapalya', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (12, 'Bangalore', 'Krishnarajapura', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (13, 'Bangalore', 'Benniganahalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (14, 'Bangalore', 'Baiyappanahalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (15, 'Bangalore', 'Swami Vivekananda Road', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (16, 'Bangalore', 'Indiranagar', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (17, 'Bangalore', 'Halasuru', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (18, 'Bangalore', 'Trinity', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (19, 'Bangalore', 'Mahatma Gandhi Road', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (20, 'Bangalore', 'Cubbon Park', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (21, 'Bangalore', 'Vidhana Soudha', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (22, 'Bangalore', 'Central College', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (23, 'Bangalore', 'Majestic', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (24, 'Bangalore', 'Krantivira Sangolli Rayanna Railway Station', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (25, 'Bangalore', 'Magadi Road', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (26, 'Bangalore', 'Sri Balagangadharanatha Swamiji Station, Hosahalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (27, 'Bangalore', 'Vijayanagara', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (28, 'Bangalore', 'Attiguppe', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (29, 'Bangalore', 'Deepanjali Nagar', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (30, 'Bangalore', 'Mysuru Road', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (31, 'Bangalore', 'Pantharapalya - Nayandahalli', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (32, 'Bangalore', 'Rajarajeshwari Nagar', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (33, 'Bangalore', 'Jnanabharathi', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (34, 'Bangalore', 'Pattanagere', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (35, 'Bangalore', 'Kengeri Bus Terminal', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (36, 'Bangalore', 'Kengeri', 'Purple', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (37, 'Bangalore', 'Challaghatta', 'Purple', 'Y');

-- Green Line
INSERT INTO station (id, city, name, line, active) VALUES (38, 'Bangalore', 'Madavara', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (39, 'Bangalore', 'Chikkabidarakallu', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (40, 'Bangalore', 'Manjunath Nagar', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (41, 'Bangalore', 'Nagasandra', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (42, 'Bangalore', 'Dasarahalli', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (43, 'Bangalore', 'Jalahalli', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (44, 'Bangalore', 'Peenya Industry', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (45, 'Bangalore', 'Peenya', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (46, 'Bangalore', 'Goraguntepalya', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (47, 'Bangalore', 'Yeshwanthpura', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (48, 'Bangalore', 'Sandal Soap Factory', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (49, 'Bangalore', 'Mahalakshmi', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (50, 'Bangalore', 'Rajajinagar', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (51, 'Bangalore', 'Mahakavi Kuvempu Road', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (52, 'Bangalore', 'Srirampura', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (53, 'Bangalore', 'Mantri Square Sampige Road', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (54, 'Bangalore', 'Majestic', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (55, 'Bangalore', 'Chickpete', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (56, 'Bangalore', 'Krishna Rajendra Market', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (57, 'Bangalore', 'National College', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (58, 'Bangalore', 'Lalbagh', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (59, 'Bangalore', 'South End Circle', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (60, 'Bangalore', 'Jayanagar', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (61, 'Bangalore', 'Rashtreeya Vidyalaya Road', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (62, 'Bangalore', 'Banashankari', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (63, 'Bangalore', 'Jaya Prakash Nagar', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (64, 'Bangalore', 'Yelachenahalli', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (65, 'Bangalore', 'Konanakunte Cross', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (66, 'Bangalore', 'Doddakallasandra', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (67, 'Bangalore', 'Vajarahalli', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (68, 'Bangalore', 'Thalaghattapura', 'Green', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (69, 'Bangalore', 'Silk Institute', 'Green', 'Y');

-- Yellow Line
INSERT INTO station (id, city, name, line, active) VALUES (70, 'Bangalore', 'Rashtreeya Vidyalaya Road', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (71, 'Bangalore', 'Ragigudda', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (72, 'Bangalore', 'Jayadeva Hospital', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (73, 'Bangalore', 'BTM Layout', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (74, 'Bangalore', 'Central Silk Board', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (75, 'Bangalore', 'Bommanahalli', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (76, 'Bangalore', 'Hongasandra', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (77, 'Bangalore', 'Kudlu Gate', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (78, 'Bangalore', 'Singasandra', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (79, 'Bangalore', 'Hosa Road', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (80, 'Bangalore', 'Beratena Agrahara', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (81, 'Bangalore', 'Electronic City', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (82, 'Bangalore', 'Infosys Foundation Konappana Agrahara', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (83, 'Bangalore', 'Huskur Road', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (84, 'Bangalore', 'Biocon Hebbagodi', 'Yellow', 'Y');
INSERT INTO station (id, city, name, line, active) VALUES (85, 'Bangalore', 'Delta Electronics Bommasandra', 'Yellow', 'Y');